/**
 * End-to-end pipeline test for the Starfish v3 stack.
 *
 * Wires the full chain through an in-memory Hono transport:
 *
 *   bootstrapRootIdentity  (alice — passphrase → root + self-signed device cap)
 *   ↓
 *   StarfishClient(capProvider)  (signs every request with cap + Ed25519 sig)
 *   ↓
 *   SyncRouter + createCapCertRoleResolver  (verifies cap, request sig, nonce)
 *   ↓
 *   createKeyringEncryptor  (HPKE-DHKEM wrap → AES-GCM)
 *   ↓
 *   round-trip: push encrypted → pull encrypted → decrypt
 *   ↓
 *   pair bob via mintDeviceCap + addRecipient → bob pushes → alice pulls
 *
 * Goal: lock the integration. Per-layer correctness lives in the unit tests.
 */

import { describe, it, expect, beforeAll } from "vitest"
import { ed25519, x25519 } from "@noble/curves/ed25519.js"
import { webcrypto } from "node:crypto"

import {
  configurePlatform,
  stableStringify,
} from "@drakkar.software/starfish-protocol"
// We import the client by relative path (NOT via the package name
// `@drakkar.software/starfish-client`) so that the e2e suite always runs
// against the latest source. The package-name resolution would hit
// `packages/ts/client/dist/`, which is regenerated by a separate
// `pnpm build` and can lag the in-tree changes (it did during the v3
// refactor when the protocol-side `host`-in-signature landed mid-flight).
// Don't "fix" this back to the package-name import without first making the
// dist build a hard prerequisite of every test run.
import { StarfishClient } from "../../../client/src/client.js"
import { SyncManager } from "../../../client/src/sync.js"
import { bootstrapRootIdentity, mintDeviceCap } from "@drakkar.software/starfish-identities"
import {
  createKeyring,
  createKeyringEncryptor,
  addRecipient as keyringAddRecipient,
} from "@drakkar.software/starfish-keyring"
import type { Keyring } from "@drakkar.software/starfish-keyring"
import type {
  StarfishCapProvider,
} from "../../../client/src/types.js"
import type { SyncSigner } from "../../../client/src/sync.js"

import {
  createSyncRouter,
  type SyncRouterOptions,
} from "../../src/router/route-builder.js"
import { MemoryObjectStore } from "../../src/storage/memory.js"
import type { SyncConfig } from "../../src/config/schema.js"
import { createCapCertRoleResolver } from "../../src/router/cap-resolver.js"
import { createInMemoryNonceCache } from "../../src/auth/nonce-cache.js"
import { createInMemoryRevocationStore } from "../../src/auth/revocation-store.js"
import { identitiesServerPlugin } from "@drakkar.software/starfish-identities"
import {
  sharingServerPlugin,
  createPublicLink,
  parsePublicLink,
  scopes,
} from "@drakkar.software/starfish-sharing"

beforeAll(() => {
  configurePlatform({
    crypto: webcrypto as unknown as Crypto,
    base64: {
      encode: (data: Uint8Array) => Buffer.from(data).toString("base64"),
      decode: (str: string) => new Uint8Array(Buffer.from(str, "base64")),
    },
  })
})

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16)
  }
  return out
}

function bytesToHex(b: Uint8Array): string {
  let s = ""
  for (let i = 0; i < b.length; i++) s += b[i]!.toString(16).padStart(2, "0")
  return s
}

/**
 * Build the dual-collection config used by every test:
 *   - `notes` (delegated) — encrypted documents at `users/{identity}/notes/{doc}`
 *   - `notes_keyring` (none) — plaintext keyring sibling at `users/{identity}/notes/_keyring`
 *
 * Mirrors the layout used by `with-keyring.test.ts`.
 */
function makeConfig(): SyncConfig {
  return {
    version: 1,
    collections: [
      {
        name: "notes",
        storagePath: "users/{identity}/notes/{doc}",
        readRoles: ["self"],
        writeRoles: ["self"],
        encryption: "delegated",
        maxBodyBytes: 1_000_000,
        allowedMimeTypes: ["application/json"],
      },
      {
        name: "notes_keyring",
        storagePath: "users/{identity}/notes/_keyring",
        readRoles: ["self"],
        writeRoles: ["self"],
        encryption: "none",
        maxBodyBytes: 1_000_000,
        allowedMimeTypes: ["application/json"],
      },
      // Plaintext public-link collection (audience caps). Read/write gated by the
      // synthesized cap roles; the resolver's `aud` membership check happens
      // before role evaluation, so a non-listed identity never reaches here.
      {
        name: "broadcast",
        storagePath: "broadcast/{doc}",
        readRoles: ["cap:read:broadcast"],
        writeRoles: ["cap:write:broadcast"],
        encryption: "none",
        maxBodyBytes: 1_000_000,
        allowedMimeTypes: ["application/json"],
      },
    ],
  }
}

interface ServerEnv {
  app: ReturnType<typeof createSyncRouter>
  store: MemoryObjectStore
}

/**
 * Spin up a real router with the cap-cert role resolver (no fakes).
 * `allowAnonymous: false` forces every request through cap verification.
 */
function makeServer(): ServerEnv {
  const store = new MemoryObjectStore(new Map())
  const opts: SyncRouterOptions = {
    store,
    config: makeConfig(),
    roleResolver: createCapCertRoleResolver({
      nonceCache: createInMemoryNonceCache(),
      revocationStore: createInMemoryRevocationStore(),
      allowAnonymous: false,
      // Compose the real extension plugins: the resolver dispatches per cap
      // kind through them (strict-kind dispatch on by default). This exercises
      // the plugin architecture end-to-end rather than the legacy inline path.
      plugins: [identitiesServerPlugin, sharingServerPlugin],
    }),
  }
  return { app: createSyncRouter(opts), store }
}

/**
 * Adapter that lets `StarfishClient` dispatch its `fetch(url, init)` calls
 * directly into the Hono app via `app.request(...)` — no real socket.
 *
 * Hono's `app.request` accepts an absolute URL string, so we can hand it the
 * URL we receive from the client without rewriting it.
 */
function makeFetchToApp(app: ServerEnv["app"]): typeof fetch {
  return (async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const url = typeof input === "string" ? input : input.toString()
    // The cap-resolver requires Content-Length on write methods (DoS guard).
    // Real fetch implementations populate it from the body buffer length; here
    // we synthesize it manually because Hono's `app.request` honours whatever
    // headers we give it verbatim.
    const next: RequestInit = { ...(init ?? {}) }
    if (
      typeof init?.body === "string" &&
      (init.method ?? "GET").toUpperCase() === "POST"
    ) {
      const cl = String(new TextEncoder().encode(init.body).byteLength)
      const headers = new Headers(init.headers ?? {})
      if (!headers.has("Content-Length")) headers.set("Content-Length", cl)
      next.headers = headers
    }
    // Hono's `app.request` accepts a fully-qualified URL but the host the
    // server reads back through `c.req.url` matches whatever we send here —
    // so the client's `baseUrl` host (signed into the request) and the
    // server-side host extraction stay symmetric.
    return app.request(url, next)
  }) as typeof fetch
}

/** Helper: build a cap provider closing over the device's edPriv. */
function capProviderFor(creds: {
  capCert: unknown
  device: { edPriv: string }
}): StarfishCapProvider {
  return {
    getCap: async () => ({
      cap: creds.capCert as never,
      devEdPrivHex: creds.device.edPriv,
    }),
  }
}

/** Helper: build a SyncSigner for the device's Ed25519 key. */
function signerFor(device: { edPub: string; edPriv: string }): SyncSigner {
  const privBytes = hexToBytes(device.edPriv)
  return {
    getSigner: async () => ({
      devEdPubHex: device.edPub,
      sign: async (bytes: Uint8Array) => ed25519.sign(bytes, privBytes),
    }),
  }
}

describe("v3 full pipeline — alice round-trip", () => {
  it("alice bootstraps, creates her keyring, pushes encrypted, pulls decrypted", async () => {
    const env = makeServer()
    const fetchAdapter = makeFetchToApp(env.app)

    // 1. Alice bootstraps. The default cap-cert from bootstrap uses
    //    `scopes.rootAll()` which has `paths: ["*"]` — `*` does not span
    //    slashes, so we re-mint Alice's device cap with a `**` path that
    //    actually matches her `users/<userId>/notes/_keyring` storage URL.
    //    A real first-device app would likely call bootstrap once and accept
    //    the rootAll cap as-is, then talk to a server whose collections live
    //    under single-segment paths — but our test uses a multi-segment tree.
    const aliceBoot = await bootstrapRootIdentity("alice-pass")
    const aliceCap = await mintDeviceCap(
      aliceBoot.device.edPriv,
      aliceBoot.device.edPub,
      {
        edPubHex: aliceBoot.device.edPub,
        kemPubHex: aliceBoot.device.kemPub,
      },
      {
        ops: ["read", "write", "list"],
        collections: ["*"],
        paths: ["**"],
      },
    )
    const alice = { ...aliceBoot, capCert: aliceCap }
    expect(alice.capCert.sub).toBe(alice.device.edPub)
    expect(alice.capCert.iss).toBe(alice.rootEdPub)
    expect(alice.userId).toHaveLength(32)

    // 2. Alice builds a keyring with herself as the only recipient,
    //    then publishes it to her notes-keyring path.
    const { keyring: initialKeyring } = await createKeyring(
      { edPrivHex: alice.device.edPriv, edPubHex: alice.device.edPub },
      [{ subKemHex: alice.device.kemPub }],
    )

    const client = new StarfishClient({
      baseUrl: "https://api.test",
      capProvider: capProviderFor(alice),
      fetch: fetchAdapter,
    })

    const keyringPath = `users/${alice.userId}/notes/_keyring`
    const kr = await client.push(
      `/push/${keyringPath}`,
      initialKeyring as unknown as Record<string, unknown>,
      null,
    )
    expect(kr.hash).toMatch(/^[0-9a-f]{64}$/)

    // 3. Build the encryptor over the keyring + alice's device KEM keys.
    const pulled = await client.pull(`/pull/${keyringPath}`)
    const fetchedKeyring = pulled.data as unknown as Keyring
    const encryptor = await createKeyringEncryptor(
      fetchedKeyring,
      { kemPubHex: alice.device.kemPub, kemPrivHex: alice.device.kemPriv },
      { trustedAdders: [alice.device.edPub] },
    )

    // 4. Encrypt + push via SyncManager so we exercise the signer plumbing too.
    const dataPath = `users/${alice.userId}/notes/note-a`
    const sync = new SyncManager({
      client,
      pullPath: `/pull/${dataPath}`,
      pushPath: `/push/${dataPath}`,
      encryptor,
      signer: signerFor(alice.device),
    })

    const plaintext = { title: "first note", body: "hello world" }
    const pushed = await sync.push(plaintext)
    expect(pushed.hash).toMatch(/^[0-9a-f]{64}$/)

    // The server stores the encrypted envelope — verify directly via store.
    const storedJson = await env.store.getString(dataPath, undefined)
    expect(storedJson).not.toBeNull()
    const storedBlob = JSON.parse(storedJson!) as {
      data: Record<string, unknown>
    }
    expect(storedBlob.data._encrypted).toEqual(expect.any(String))
    expect(storedBlob.data._epoch).toBe(fetchedKeyring.currentEpoch)
    // Signer plumbing was exercised: authorPubkey + authorSignature attached.
    expect(storedBlob.data.authorPubkey).toBe(alice.device.edPub)
    expect(typeof storedBlob.data.authorSignature).toBe("string")
    // The plaintext title is NOT visible to the server.
    expect(stableStringify(storedBlob.data)).not.toContain("first note")

    // 5. Pull via SyncManager — encryptor.decrypt round-trips the plaintext.
    const sync2 = new SyncManager({
      client,
      pullPath: `/pull/${dataPath}`,
      pushPath: `/push/${dataPath}`,
      encryptor,
    })
    const pulledNote = await sync2.pull()
    // SyncManager strips author fields into the encrypted envelope before decrypt;
    // the decrypted plaintext is what we pushed.
    expect(pulledNote.data).toMatchObject(plaintext)
  })
})

describe("v3 full pipeline — pair bob, push from bob, pull as alice", () => {
  it("alice mints bob's device cap, adds bob to keyring; bob encrypts; alice decrypts", async () => {
    const env = makeServer()
    const fetchAdapter = makeFetchToApp(env.app)

    // ── Alice bootstraps (re-mint cap with `**` path so multi-segment storage URLs match — see comment in the first test). ──
    const aliceBoot = await bootstrapRootIdentity("alice-pair-pass")
    const aliceCap = await mintDeviceCap(
      aliceBoot.device.edPriv,
      aliceBoot.device.edPub,
      {
        edPubHex: aliceBoot.device.edPub,
        kemPubHex: aliceBoot.device.kemPub,
      },
      {
        ops: ["read", "write", "list"],
        collections: ["*"],
        paths: ["**"],
      },
    )
    const alice = { ...aliceBoot, capCert: aliceCap }
    const aliceClient = new StarfishClient({
      baseUrl: "https://api.test",
      capProvider: capProviderFor(alice),
      fetch: fetchAdapter,
    })

    // ── Alice publishes the keyring with herself only ──
    const { keyring: initial, cek } = await createKeyring(
      { edPrivHex: alice.device.edPriv, edPubHex: alice.device.edPub },
      [{ subKemHex: alice.device.kemPub }],
    )
    const keyringPath = `users/${alice.userId}/notes/_keyring`
    const keyringPushRes = await aliceClient.push(
      `/push/${keyringPath}`,
      initial as unknown as Record<string, unknown>,
      null,
    )

    // ── Bob's device generates its own Ed25519 + X25519 keypair ──
    const bobEdPriv = webcrypto.getRandomValues(new Uint8Array(32))
    const bobEdPub = ed25519.getPublicKey(bobEdPriv)
    const bobKemPriv = webcrypto.getRandomValues(new Uint8Array(32))
    const bobKemPub = x25519.getPublicKey(bobKemPriv)
    const bobDevice = {
      edPriv: bytesToHex(bobEdPriv),
      edPub: bytesToHex(bobEdPub),
      kemPriv: bytesToHex(bobKemPriv),
      kemPub: bytesToHex(bobKemPub),
    }

    // ── Alice mints a device cap for Bob acting as her proxy ──
    //
    // Bob's cap must cover the URL prefix where the data lives:
    // `/push/users/<alice.userId>/notes/{doc}` and the keyring sibling.
    // We grant the full `users/<alice.userId>/notes/**` subtree.
    const bobCap = await mintDeviceCap(
      alice.device.edPriv,
      alice.device.edPub,
      { edPubHex: bobDevice.edPub, kemPubHex: bobDevice.kemPub },
      {
        ops: ["read", "write", "list"],
        collections: ["notes", "notes_keyring"],
        paths: [`users/${alice.userId}/notes/**`],
      },
    )
    expect(bobCap.sub).toBe(bobDevice.edPub)
    expect(bobCap.iss).toBe(alice.device.edPub)
    expect(bobCap.issUserId).toBe(alice.userId)

    // ── Alice adds Bob as a recipient on her keyring (operating in-memory) ──
    const keyringNext = await keyringAddRecipient(
      initial,
      { edPrivHex: alice.device.edPriv, edPubHex: alice.device.edPub },
      cek,
      bobDevice.kemPub,
    )
    // Push the updated keyring with baseHash = the prior push hash.
    await aliceClient.push(
      `/push/${keyringPath}`,
      keyringNext as unknown as Record<string, unknown>,
      keyringPushRes.hash,
    )

    // ── Bob's client — different cap, different signing key ──
    const bobClient = new StarfishClient({
      baseUrl: "https://api.test",
      capProvider: {
        getCap: async () => ({
          cap: bobCap,
          devEdPrivHex: bobDevice.edPriv,
        }),
      },
      fetch: fetchAdapter,
    })

    // Bob pulls the keyring (his cap covers the keyring path) and builds an encryptor.
    const krFromBob = await bobClient.pull(`/pull/${keyringPath}`)
    const bobsKeyring = krFromBob.data as unknown as Keyring
    const bobEncryptor = await createKeyringEncryptor(
      bobsKeyring,
      { kemPubHex: bobDevice.kemPub, kemPrivHex: bobDevice.kemPriv },
      { trustedAdders: [alice.device.edPub] },
    )

    // ── Bob pushes an encrypted note ──
    //
    // Note path lives in Alice's storage tree — that's the whole point of
    // device pairing: Bob acts as Alice's proxy.
    const notePath = `users/${alice.userId}/notes/from-bob`
    const bobSync = new SyncManager({
      client: bobClient,
      pullPath: `/pull/${notePath}`,
      pushPath: `/push/${notePath}`,
      encryptor: bobEncryptor,
      signer: signerFor(bobDevice),
    })
    const note = { author: "bob", body: "hi alice" }
    const pushRes = await bobSync.push(note)
    expect(pushRes.hash).toMatch(/^[0-9a-f]{64}$/)

    // Server stored an encrypted envelope authored by Bob's device key.
    const storedJson = await env.store.getString(notePath, undefined)
    expect(storedJson).not.toBeNull()
    const storedBlob = JSON.parse(storedJson!) as { data: Record<string, unknown> }
    expect(storedBlob.data._encrypted).toEqual(expect.any(String))
    expect(storedBlob.data.authorPubkey).toBe(bobDevice.edPub)

    // ── Alice pulls + decrypts Bob's note (alice's encryptor uses her own KEM key) ──
    const aliceEncryptor = await createKeyringEncryptor(
      keyringNext,
      { kemPubHex: alice.device.kemPub, kemPrivHex: alice.device.kemPriv },
      { trustedAdders: [alice.device.edPub] },
    )
    const aliceSync = new SyncManager({
      client: aliceClient,
      pullPath: `/pull/${notePath}`,
      pushPath: `/push/${notePath}`,
      encryptor: aliceEncryptor,
    })
    const result = await aliceSync.pull()
    expect(result.data).toMatchObject(note)
  })
})

describe("v3 full pipeline — public link (audience cap)", () => {
  it("alice mints a restricted writer link; bob redeems and round-trips a plaintext doc; a non-listed identity is rejected 403", async () => {
    const env = makeServer()
    const fetchAdapter = makeFetchToApp(env.app)

    const alice = await bootstrapRootIdentity("alice-link-pass")
    const bob = await bootstrapRootIdentity("bob-link-pass")
    const carol = await bootstrapRootIdentity("carol-link-pass")

    // Alice mints a writer public link restricted to Bob, then shares the fragment.
    const link = await createPublicLink({
      issEdPrivHex: alice.device.edPriv,
      issEdPubHex: alice.device.edPub,
      collection: "broadcast",
      scope: scopes.writer("broadcast"),
      allowedIdentities: [bob.device.edPub],
    })
    const parsed = parsePublicLink(link.fragment)
    expect(parsed.cap.kind).toBe("audience")

    // Bob redeems via a real StarfishClient: the cap provider returns the
    // audience cap, Bob's OWN signing key, and his pubHex (→ X-Starfish-Pub).
    const bobClient = new StarfishClient({
      baseUrl: "https://api.test",
      capProvider: {
        getCap: async () => ({
          cap: parsed.cap as never,
          devEdPrivHex: bob.device.edPriv,
          pubHex: bob.device.edPub,
        }),
      },
      fetch: fetchAdapter,
    })

    const docPath = "broadcast/post-1"
    const pushed = await bobClient.push(
      `/push/${docPath}`,
      { hello: "from bob" },
      null,
    )
    expect(pushed.hash).toMatch(/^[0-9a-f]{64}$/)

    // Read it back through the full stack; stored in plaintext (encryption: none).
    const pulled = await bobClient.pull(`/pull/${docPath}`)
    expect(pulled.data).toMatchObject({ hello: "from bob" })
    const stored = await env.store.getString(docPath, undefined)
    expect(stored).toContain("from bob")

    // Carol holds the same link but is NOT in `aud` → 403 (her signature is
    // valid for her own key, but membership fails).
    const carolClient = new StarfishClient({
      baseUrl: "https://api.test",
      capProvider: {
        getCap: async () => ({
          cap: parsed.cap as never,
          devEdPrivHex: carol.device.edPriv,
          pubHex: carol.device.edPub,
        }),
      },
      fetch: fetchAdapter,
    })
    await expect(carolClient.pull(`/pull/${docPath}`)).rejects.toMatchObject({ status: 403 })
  })
})
