"""Cross-language Parquet compatibility tests.

Verifies that the Python ``encode_parquet`` output is schema-compatible with
the TypeScript ``encodeParquet`` (``hyparquet-writer``) and can be decoded by
any standard Parquet reader (pyarrow, DuckDB, etc.).

Two complementary directions:
1. **Python → any reader**: Python-encoded Parquet decoded by pyarrow must
   produce the expected schema and values.
2. **TS → Python reader**: The committed ``tests/fixtures/ts_reference.parquet``
   (generated by ``hyparquet-writer``) must be decodable by pyarrow with the
   same 10-column schema and the expected values.

Both producers target the same logical schema (10 STRING columns, uncompressed)
so that DuckDB queries via ``read_parquet('s3://…/**/*.parquet')`` work
identically on files from either backend.

The TS reference fixture was generated with::

    import { parquetWriteBuffer } from "hyparquet-writer"
    const COLUMNS = ["event_type","event","distinct_id","anonymous_id","ts",
                     "message_id","properties","context","dt","received_at"]
    const rows = [
      { event_type:"capture", event:"button_clicked", ... received_at:"..." },
      { event_type:"screen",  event:"page_viewed",    ... received_at:"..." },
    ]
    const columnData = COLUMNS.map(n => ({ name:n, type:"STRING", nullable:false,
                                           data: rows.map(r => String(r[n] ?? "")) }))
    const bytes = parquetWriteBuffer({ columnData, codec:"UNCOMPRESSED" })
    writeFileSync("tests/fixtures/ts_reference.parquet", Buffer.from(bytes))
"""

from __future__ import annotations

import io
import os

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from starfish_events.encode import COLUMNS, encode_parquet

# ---------------------------------------------------------------------------
# Reference data (identical input to both encoders)
# ---------------------------------------------------------------------------

_TS_ROWS = [
    {
        "event_type": "capture",
        "event": "button_clicked",
        "distinct_id": "user-abc",
        "anonymous_id": "anon-xyz",
        "ts": "2024-06-01T10:00:00.000Z",
        "message_id": "msg-001",
        "properties": '{"label":"Submit"}',
        "context": '{"platform":"web"}',
        "dt": "2024-06-01",
        "received_at": "2024-06-01T10:00:01.000Z",
    },
    {
        "event_type": "screen",
        "event": "page_viewed",
        "distinct_id": "user-def",
        "anonymous_id": "anon-uvw",
        "ts": "2024-06-01T11:00:00.000Z",
        "message_id": "msg-002",
        "properties": '{"page":"/home"}',
        "context": '{"platform":"ios"}',
        "dt": "2024-06-01",
        "received_at": "2024-06-01T11:00:01.000Z",
    },
]

_FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
_TS_FIXTURE = os.path.join(_FIXTURES_DIR, "ts_reference.parquet")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_schema_names(path_or_bytes) -> list[str]:
    if isinstance(path_or_bytes, bytes):
        return pq.read_schema(io.BytesIO(path_or_bytes)).names
    return pq.read_schema(path_or_bytes).names


def _read_table(path_or_bytes) -> pa.Table:
    if isinstance(path_or_bytes, bytes):
        return pq.read_table(io.BytesIO(path_or_bytes))
    return pq.read_table(path_or_bytes)


# ---------------------------------------------------------------------------
# Python → any reader: schema compatibility
# ---------------------------------------------------------------------------


def test_python_encoder_schema_matches_ts_spec():
    """Python encoder must produce exactly the same 10-column schema as the TS spec."""
    data = encode_parquet(_TS_ROWS)
    assert _read_schema_names(data) == list(COLUMNS)


def test_python_encoder_all_columns_are_utf8_string():
    """All columns must be UTF-8 string type — matches the TS ``type:"STRING"``."""
    data = encode_parquet(_TS_ROWS)
    schema = pq.read_schema(io.BytesIO(data))
    for field in schema:
        assert pa.types.is_string(field.type) or pa.types.is_large_string(field.type), (
            f"Column '{field.name}' should be STRING, got {field.type}"
        )


def test_python_encoder_row_count_matches_input():
    data = encode_parquet(_TS_ROWS)
    table = _read_table(data)
    assert table.num_rows == len(_TS_ROWS)


def test_python_encoder_values_match_input():
    data = encode_parquet(_TS_ROWS)
    table = _read_table(data)
    cols = table.to_pydict()
    assert cols["event"] == ["button_clicked", "page_viewed"]
    assert cols["event_type"] == ["capture", "screen"]
    assert cols["distinct_id"] == ["user-abc", "user-def"]
    assert cols["anonymous_id"] == ["anon-xyz", "anon-uvw"]
    assert cols["message_id"] == ["msg-001", "msg-002"]
    assert cols["dt"] == ["2024-06-01", "2024-06-01"]


# ---------------------------------------------------------------------------
# TS → Python reader: the TS-generated fixture must be readable by pyarrow
# ---------------------------------------------------------------------------


@pytest.fixture
def ts_fixture_bytes() -> bytes:
    if not os.path.exists(_TS_FIXTURE):
        pytest.skip(f"TS reference fixture not found at {_TS_FIXTURE}")
    with open(_TS_FIXTURE, "rb") as fh:
        return fh.read()


def test_ts_fixture_is_valid_parquet_magic(ts_fixture_bytes):
    """TS-generated Parquet must have PAR1 magic (decodable by any reader)."""
    assert ts_fixture_bytes[:4] == b"PAR1"
    assert ts_fixture_bytes[-4:] == b"PAR1"


def test_ts_fixture_schema_matches_expected_columns(ts_fixture_bytes):
    """TS fixture schema must match the 10-column spec — same as Python encoder."""
    assert _read_schema_names(ts_fixture_bytes) == list(COLUMNS)


def test_ts_fixture_all_columns_are_string_type(ts_fixture_bytes):
    schema = pq.read_schema(io.BytesIO(ts_fixture_bytes))
    for field in schema:
        assert pa.types.is_string(field.type) or pa.types.is_large_string(field.type), (
            f"TS column '{field.name}' should be STRING, got {field.type}"
        )


def test_ts_fixture_correct_row_count(ts_fixture_bytes):
    table = _read_table(ts_fixture_bytes)
    assert table.num_rows == 2


def test_ts_fixture_values_readable_by_pyarrow(ts_fixture_bytes):
    """Core cross-language test: pyarrow can decode the TS-produced Parquet and get expected values."""
    table = _read_table(ts_fixture_bytes)
    cols = table.to_pydict()
    # Verify both rows fully decode correctly.
    assert cols["event"] == ["button_clicked", "page_viewed"]
    assert cols["event_type"] == ["capture", "screen"]
    assert cols["distinct_id"] == ["user-abc", "user-def"]
    assert cols["message_id"] == ["msg-001", "msg-002"]
    assert cols["properties"] == ['{"label":"Submit"}', '{"page":"/home"}']
    assert cols["received_at"] == [
        "2024-06-01T10:00:01.000Z",
        "2024-06-01T11:00:01.000Z",
    ]


# ---------------------------------------------------------------------------
# Schema equivalence: Python output == TS output (column names and types)
# ---------------------------------------------------------------------------


def test_python_and_ts_produce_equivalent_logical_schema(ts_fixture_bytes):
    """Both encoders must produce identical column name lists and string types.

    The actual byte representation will differ (pyarrow vs hyparquet-writer
    produce different Parquet implementations) but the logical schema — which is
    what DuckDB reads — must be identical.
    """
    py_bytes = encode_parquet(_TS_ROWS)
    py_schema = pq.read_schema(io.BytesIO(py_bytes))
    ts_schema = pq.read_schema(io.BytesIO(ts_fixture_bytes))

    assert py_schema.names == ts_schema.names, (
        f"Python columns: {py_schema.names}\nTS columns: {ts_schema.names}"
    )
    for py_field, ts_field in zip(py_schema, ts_schema):
        assert py_field.name == ts_field.name
        # Both must be some flavour of string (utf8 vs large_utf8 are both fine).
        assert pa.types.is_string(py_field.type) or pa.types.is_large_string(py_field.type)
        assert pa.types.is_string(ts_field.type) or pa.types.is_large_string(ts_field.type)


def test_python_and_ts_produce_same_decoded_values(ts_fixture_bytes):
    """Both encoders must decode to identical data for the same input."""
    py_bytes = encode_parquet(_TS_ROWS)
    py_cols = _read_table(py_bytes).to_pydict()
    ts_cols = _read_table(ts_fixture_bytes).to_pydict()

    for col in COLUMNS:
        assert py_cols[col] == ts_cols[col], (
            f"Column '{col}' differs:\n  Python: {py_cols[col]}\n  TS: {ts_cols[col]}"
        )
